### ISSUE TITLE
Windows stype jvmtop.sh

### ISSUE THREAD

**Issue by Herschdorfer** [patric-r/jvmtop#87]
hey guys,

just cloned this and build it via mvn on a windows machine. After that the jvmtop.sh had windows style line endings resulting in 

-bash: ./jvmtop.sh: /bin/sh^M: bad interpreter: No such file or directory

easy fix, but donno if this is intended like this... ;)

**Comment by patric-r** [comment]
This seems to be not an issue with jvmtop.sh itself rather than git/your environment.
If you clone a git repository using the windows git client, you get windows-style line delimiters (by default) in all text files. They cannot be used with bash.
Additionally, git might also get [confused when running in a cygwin environment](http://stackoverflow.com/questions/15717077/line-endings-with-cygwin-and-github-for-windows)

Please adjust your environment.
See also [here](https://help.github.com/articles/dealing-with-line-endings/).

**Comment by Herschdorfer** [comment]
this is what i just found and pushed a small fix for this. Checked on my fork and was working.

#88

**Comment by patric-r** [comment]
Thank you, that's the way to go.

**Comment by Herschdorfer** [comment]
thx for merging!
