### ISSUE TITLE
how the jvmtop tools to monitor other user's jvm process? 

### ISSUE THREAD

**Issue by panshiming** [Patric-R/jvmtop#93]
In my work, I need to monitor all the jvm process of one machine, and these jvm process are not under same users, so it is very urgent to monitor target process run under the different user as jvmtop , is there any way to solve this case? thanks

**Comment by patric-r** [comment]
You can try running jvmtop as root. But depending on your actual JDK this might or might not solve your problem.
Due to security constraints within the JDK other users processes cannot be monitored.
(Un)fortunately, these cannot be bypassed (except for root in some cases).

Please note the [FAQ](https://github.com/patric-r/jvmtop/blob/master/doc/FAQ.md), too.

**Comment by panshiming** [comment]
Very unfortunately, when running jvmtop as root , it still can not work!
